schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "VpcEnvironmentInput"

  types:
    VpcEnvironmentInput:
      type: object
      description: "Input properties for a vpc environment."
      properties:
        vpc_name:
          type: string
          description: "Name for vpc"
        az:
          type: string
          description: "The az you want your environment to deployed to, e.g. us-east-1a"
          minLength: 1
          maxLength: 30
      required:
        - vpc_name
        - az
